# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tillandsia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tilly.Species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TillyPic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tillys/%y/%m')),
                ('tillandsia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilly.Tillandsia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
