# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:32
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tilly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tillypic',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='tillys/%y/%m'),
        ),
    ]
