# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilly', '0002_auto_20161121_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='tillandsia',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
