# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilly', '0003_tillandsia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='species',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tillandsia',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tillandsia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tillypic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tillypic',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
