# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilly', '0004_auto_20161121_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tillandsia',
            options={'ordering': ['name']},
        ),
    ]
